name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet publish -c Release -o publish -p:PublishReadyToRun=true -p:PublishSingleFile=true --self-contained true -p:IncludeNativeLibrariesForSelfExtract=true
    - name: dir 1
      run: dir D:\a\CityLauncher\CityLauncher\bin\Release\net6.0-windows\win-x64\
    - name: dir 2
      run: dir  D:\a\CityLauncher\CityLauncher\publish\
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: EXE App
        path: D:\a\CityLauncher\CityLauncher\publish\CityLauncher.exe