name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore -r win10-x86
    - name: Build
      run: dotnet build --configuration Release --no-restore -r win10-x86
    - name: Test
      run: dotnet test --configuration Release --no-restore --no-build --verbosity normal -r win10-x86
